name: aml-register-model

on:
  repository_dispatch:
    types: [run-completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check variables
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload.data) }}
        run: |
          if [ -z "${{ github.event.client_payload.data.experimentName }}"]; then echo "experiment id is NULL"; exit 1; else echo "model_name is ${{ toJson(github.event.client_payload.data.experimentName) }}"; fi;
          if [ -z "${{ github.event.client_payload.data.runId }}"]; then echo "runId is NULL"; exit 1; else echo "model_version is ${{ toJson(github.event.client_payload.data.runId) }}"; fi;
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
    
      - name: Connect/Create Azure Machine Learning Workspace
        id: aml_workspace
        uses: Azure/aml-workspace@v1
        with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      # # Register model in Azure Machine Learning model registry
      - name: Register model
        id: aml_registermodel
        uses: Azure/aml-registermodel@ashishonce/adddefaulttags
        with:
             azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
             run_id:  ${{ github.event.client_payload.data.runId }}
             experiment_name: ${{ github.event.client_payload.data.experimentName }}


